locale: "fr"
crates:
  maximum-player-rewards: 135
  resolvers:
    0: # This resolver should always be present to ensure basic "by-name" resolving
      class: fr.theoszanto.mc.crateexpress.resolvers.SimpleCrateResolver
    1:
      class: fr.theoszanto.mc.crateexpress.resolvers.CaseInsensitiveCrateResolver
    2:
      class: fr.theoszanto.mc.crateexpress.resolvers.UpperNamespaceCrateResolver
#    3:
#      class: fr.theoszanto.mc.crateexpress.resolvers.BindingsCrateResolver
#      options:
#        - alias1: KeyName1
#          alias2: KeyName2
rewards:
  item:
    gui-class: fr.theoszanto.mc.crateexpress.models.gui.reward.CrateItemRewardGUI
    gui-icon: ITEM_FRAME
  key:
    gui-class: fr.theoszanto.mc.crateexpress.models.gui.reward.CrateKeyRewardGUI
    gui-icon: TRIPWIRE_HOOK
  money:
    gui-class: fr.theoszanto.mc.crateexpress.models.gui.reward.CrateMoneyRewardGUI
    gui-icon: EMERALD
  command:
    gui-class: fr.theoszanto.mc.crateexpress.models.gui.reward.CrateCommandRewardGUI
    gui-icon: COMMAND_BLOCK
  other:
    gui-class: fr.theoszanto.mc.crateexpress.models.gui.reward.CrateOtherRewardGUI
    gui-icon: CHEST
storage:
  source:
    class: fr.theoszanto.mc.crateexpress.storage.YamlCrateStorage
    options:
      - "./crates/"
      - "./rewards/"
  rewards:
    0:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateItemRewardYML
    1:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateKeyRewardYML
    2:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateMoneyRewardYML
    3:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateCommandRewardYML
    4:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateOtherRewardYML
    5:
      class: fr.theoszanto.mc.crateexpress.storage.yaml.CrateUnknownRewardYML
money:
  # Be careful not to include any leading slash!
  give-command: "money give <player> <amount>"
  item: PAPER
  currency-symbol: "$"
  placement: before
  physical: false
export:
  directory: "./exports/"
  exporters:
    0:
      class: fr.theoszanto.mc.crateexpress.exporters.CSVCrateExporter
